# Generated by Django 4.2.5 on 2023-11-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpeg/', null=True, upload_to='profile_pictures/'),
        ),
    ]
