# Generated by Django 4.2.5 on 2023-11-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='area',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='email_notifications_active',
        ),
    ]
