# Generated by Django 4.2.5 on 2023-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_listing_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
    ]
