# Generated by Django 4.2.5 on 2023-11-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_useraccount_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.area'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email_notifications_active',
            field=models.BooleanField(default=True),
        ),
    ]
