# Generated by Django 4.2.5 on 2023-11-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listing_isbookmarked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'listing')},
        ),
    ]
