# Generated by Django 4.2.5 on 2023-11-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_useraccount_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email_notifications_active',
            field=models.BooleanField(default=False),
        ),
    ]
