# Generated by Django 4.2.5 on 2023-11-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isBookmarked',
        ),
    ]
