# Generated by Django 4.2.5 on 2023-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_useraccount_email_notifications_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email_notifications_active',
            field=models.BooleanField(default=True),
        ),
    ]
